"""Generate runtime FaunaSpecies resources and the population scene.

This file is the editable catalogue. The Blender recipe owns geometry, UVs,
COLOR_0, paint PNGs, previews, and the asset manifest; this catalogue owns
habitat, appearance tuning, health, disposition, locomotion, moves, combat, and
streaming density.
"""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
FAUNA_DIR = ROOT / "game" / "fauna"
SPECIES_DIR = FAUNA_DIR / "species"
MATERIAL_DIR = FAUNA_DIR / "materials"
SCENE_PATH = FAUNA_DIR / "fauna_populations.tscn"


SPECIES = (
    {
        "id": "lumaquill_porcupine",
        "display_name": "Lumaquill Porcupine",
        "model": "lumaquill_porcupine",
        "enabled": True,
        "disposition": 1,  # PASSIVE
        "move_set": 7,  # WALK | RUN | ATTACK (contact quills)
        "locomotion": 0,  # WALKER
        "attack_style": 1,  # CONTACT
        "paint_style": (
            "Broad turquoise flank bands, magenta quill chevrons, large yellow "
            "eyespots, and mip-safe cyan/magenta night marks"
        ),
        "height": 0.72,
        "height_variation": 0.10,
        "variant_tint_a": (0.84, 1.0, 1.0, 1.0),
        "variant_tint_b": (1.0, 0.76, 0.94, 1.0),
        "saturation": 1.38,
        "brightness": 1.10,
        "biome_tint_strength": 0.13,
        "night_emission_color": (0.15, 0.94, 1.0, 1.0),
        "night_emission_energy": 2.15,
        "night_emission_albedo": 0.62,
        "night_pulse_amount": 0.16,
        "night_pulse_speed": 0.34,
        "local_light_color": (0.12, 0.82, 1.0, 1.0),
        "local_light_energy": 1.45,
        "local_light_range": 7.5,
        "local_light_height_share": 0.58,
        "collision_radius_share": 0.42,
        "collision_height_share": 0.78,
        "combat_radius_share": 0.47,
        "ground_layer": 1,  # GRASS
        "minimum_ground_claim": 0.05,
        "above_water": 4.0,
        "below": 380.0,
        "minimum_arid": 0.0,
        "maximum_arid": 0.78,
        "minimum_frost": 0.0,
        "maximum_frost": 0.82,
        "max_slope": 27.0,
        "steady_over": 1.6,
        "steady_within": 0.82,
        "global_population": True,
        "cell_size": 82.0,
        "spawn_chance": 0.22,
        "pack_min": 2,
        "pack_max": 4,
        "pack_radius": 5.5,
        "maximum_instances": 10,
        "spawn_within": 210.0,
        "despawn_beyond": 278.0,
        "random_seed": 20268131,
        "colony_count": 4,
        "colony_near": 30.0,
        "colony_far": 62.0,
        "health": 62.0,
        "health_per_metre": 12.0,
        "toughness": 0,  # SOFT
        "respawn_delay": 16.0,
        "walk_speed": 1.65,
        "run_speed": 4.7,
        "move_acceleration": 18.0,
        "turn_speed": 8.0,
        "wander_radius": 17.0,
        "wander_pause": 2.5,
        "notice_range": 12.0,
        "flee_range": 7.5,
        "physics_within": 45.0,
        "quadruped_gait": True,
        "leg_mask_color": (0.09, 0.14, 0.23, 1.0),
        "leg_mask_tolerance": 0.16,
        "gait_stride_share": 0.88,
        "gait_swing_share": 0.14,
        "gait_lift_share": 0.06,
        "gait_leg_top_share": 0.43,
        "body_rock_degrees": 7.5,
        "body_bob_share": 0.032,
        "attack_damage": 9.0,
        "attack_range": 0.08,
        "attack_radius": 0.52,
        "attack_windup": 0.0,
        "attack_cooldown": 0.85,
        "attack_knockback": 4.0,
        "roughness": 0.55,
        "specular": 0.32,
        "texture_relief": 1.25,
        "detail_scale": 10.0,
        "detail_amount": 0.12,
        "bump_scale": 15.0,
        "bump_strength": 0.13,
        "macro_scale": 1.1,
        "macro_amount": 0.10,
        "camera_rim_color": (0.12, 0.94, 1.0, 1.0),
        "camera_rim_energy": 0.34,
    },
    {
        "id": "prism_coil_slinky",
        "display_name": "Prism-Coil Slinky",
        "model": "prism_coil_slinky",
        "enabled": False,
        "disposition": 2,  # HOSTILE
        "move_set": 7,  # WALK | RUN | ATTACK
        "locomotion": 2,  # END_OVER_END
        "attack_style": 2,  # BODY_SLAP
        "paint_style": (
            "Wide violet/teal coil bands, looping lime helix marks, pink slap "
            "pads, and a mip-safe luminous stripe mask"
        ),
        "height": 1.70,
        "height_variation": 0.08,
        "variant_tint_a": (0.90, 0.78, 1.0, 1.0),
        "variant_tint_b": (0.76, 1.0, 0.92, 1.0),
        "saturation": 1.48,
        "brightness": 1.11,
        "biome_tint_strength": 0.10,
        "night_emission_color": (0.30, 1.0, 0.78, 1.0),
        "night_emission_energy": 2.45,
        "night_emission_albedo": 0.56,
        "night_pulse_amount": 0.22,
        "night_pulse_speed": 0.25,
        "local_light_color": (0.34, 1.0, 0.72, 1.0),
        "local_light_energy": 1.8,
        "local_light_range": 10.5,
        "local_light_height_share": 0.52,
        "collision_radius_share": 0.43,
        "collision_height_share": 0.96,
        "combat_radius_share": 0.49,
        "ground_layer": 0,  # ANYWHERE
        "minimum_ground_claim": 0.0,
        "above_water": 5.0,
        "below": 460.0,
        "minimum_arid": 0.0,
        "maximum_arid": 1.0,
        "minimum_frost": 0.0,
        "maximum_frost": 0.94,
        "max_slope": 22.0,
        "steady_over": 2.6,
        "steady_within": 1.05,
        "global_population": True,
        "cell_size": 86.0,
        "spawn_chance": 0.15,
        "pack_min": 1,
        "pack_max": 2,
        "pack_radius": 7.0,
        "maximum_instances": 9,
        "spawn_within": 235.0,
        "despawn_beyond": 305.0,
        "random_seed": 20268132,
        "colony_count": 2,
        "colony_near": 54.0,
        "colony_far": 86.0,
        "health": 170.0,
        "health_per_metre": 28.0,
        "toughness": 1,  # WOODY
        "respawn_delay": 20.0,
        "walk_speed": 2.2,
        "run_speed": 7.2,
        "move_acceleration": 22.0,
        "turn_speed": 6.0,
        "wander_radius": 23.0,
        "wander_pause": 1.7,
        "notice_range": 21.0,
        "flee_range": 0.0,
        "physics_within": 55.0,
        "attack_damage": 22.0,
        "attack_range": 2.35,
        "attack_radius": 1.1,
        "attack_windup": 0.42,
        "attack_cooldown": 2.25,
        "attack_knockback": 10.5,
        "roughness": 0.40,
        "specular": 0.50,
        "texture_relief": 1.05,
        "detail_scale": 7.0,
        "detail_amount": 0.09,
        "bump_scale": 11.0,
        "bump_strength": 0.10,
        "macro_scale": 0.72,
        "macro_amount": 0.08,
        "camera_rim_color": (0.64, 0.32, 1.0, 1.0),
        "camera_rim_energy": 0.42,
    },
    {
        "id": "aurora_fleece_alpaca",
        "display_name": "Aurora-Fleece Alpaca",
        "model": "aurora_fleece_alpaca",
        "enabled": True,
        "disposition": 0,  # FRIENDLY
        # Attack is in the move set, but it is only ever reached by hurting one:
        # a friendly animal has no attack behaviour until it is provoked.
        "move_set": 7,  # WALK | RUN | ATTACK
        "locomotion": 0,  # WALKER
        "attack_style": 3,  # SPIT
        "paint_style": (
            "Pale lilac fleece streaks, a broad aurora-blue saddle, cream face "
            "and throat, indigo socks, magenta tail plume, and mip-safe "
            "luminous flank rosettes"
        ),
        "height": 1.30,
        "height_variation": 0.09,
        "variant_tint_a": (1.0, 0.94, 1.0, 1.0),
        "variant_tint_b": (0.88, 0.97, 1.0, 1.0),
        # Wool is pale by nature, and a pale palette under a bright sun washes
        # out to a white toy. The chroma is pushed and the brightness pulled back
        # so the saddle, socks, and plume still read at gameplay distance.
        "saturation": 1.45,
        "brightness": 0.99,
        "biome_tint_strength": 0.10,
        "night_emission_color": (0.46, 1.0, 0.92, 1.0),
        "night_emission_energy": 1.85,
        "night_emission_albedo": 0.50,
        "night_pulse_amount": 0.13,
        "night_pulse_speed": 0.22,
        "local_light_color": (0.44, 1.0, 0.90, 1.0),
        "local_light_energy": 1.25,
        "local_light_range": 8.5,
        "local_light_height_share": 0.62,
        "collision_radius_share": 0.31,
        "collision_height_share": 0.80,
        "combat_radius_share": 0.44,
        "ground_layer": 1,  # GRASS
        "minimum_ground_claim": 0.05,
        "above_water": 4.0,
        "below": 360.0,
        "minimum_arid": 0.0,
        "maximum_arid": 0.72,
        "minimum_frost": 0.0,
        "maximum_frost": 0.78,
        "max_slope": 24.0,
        "steady_over": 2.2,
        "steady_within": 1.0,
        # A colony-site herd only, for now: this one is being watched before it
        # is turned loose on every grassland on the planet.
        "global_population": False,
        "cell_size": 90.0,
        "spawn_chance": 0.18,
        "pack_min": 2,
        "pack_max": 4,
        "pack_radius": 7.5,
        "maximum_instances": 8,
        "spawn_within": 200.0,
        "despawn_beyond": 268.0,
        "random_seed": 20268133,
        "colony_count": 5,
        "colony_near": 20.0,
        "colony_far": 54.0,
        "health": 120.0,
        "health_per_metre": 20.0,
        "toughness": 0,  # SOFT
        "respawn_delay": 22.0,
        "walk_speed": 1.55,
        "run_speed": 6.2,
        "move_acceleration": 20.0,
        "turn_speed": 7.5,
        "wander_radius": 20.0,
        "wander_pause": 2.8,
        "notice_range": 16.0,
        "flee_range": 8.5,
        "physics_within": 50.0,
        "graze": True,
        "graze_chance": 0.62,
        "graze_seconds": 5.5,
        "bound_when_fleeing": True,
        "provoked_seconds": 9.0,
        "strafe_radius": 7.5,
        "strafe_speed": 4.6,
        "skeletal_clips": True,
        "clip_speed_scale": 1.15,
        "clip_blend": 0.18,
        "attack_damage": 7.0,
        # Reach is the spit's, not a bite's: it opens fire from across the ring
        # it is holding, and the windup matches the throw in the Spit clip.
        "attack_range": 14.0,
        "attack_radius": 0.62,
        "attack_windup": 0.45,
        "attack_cooldown": 1.9,
        "attack_knockback": 3.2,
        "attack_parryable": True,
        "spit_from_height_share": 0.82,
        "spit_from_forward_share": 0.60,
        "spit_speed": 18.0,
        "spit_gravity": 8.5,
        "spit_ball_radius": 0.13,
        "spit_hit_radius": 0.62,
        "spit_color": (0.60, 0.94, 1.0, 1.0),
        "spit_glow": 1.9,
        "roughness": 0.68,
        "specular": 0.24,
        "texture_relief": 1.45,
        "detail_scale": 13.0,
        "detail_amount": 0.16,
        "bump_scale": 19.0,
        "bump_strength": 0.17,
        "macro_scale": 1.3,
        "macro_amount": 0.12,
        "camera_rim_color": (0.52, 1.0, 0.94, 1.0),
        "camera_rim_energy": 0.30,
    },
    {
        "id": "tide_latch_crab",
        "display_name": "Tide-Latch Crab",
        "model": "tide_latch_crab",
        "enabled": True,
        "disposition": 1,  # PASSIVE
        "move_set": 7,
        "locomotion": 0,
        "attack_style": 1,  # CONTACT
        "paint_style": (
            "Coral carapace bands, cream belly, teal limb joints, gold claw "
            "plates, cyan eye-glow discs, and magenta pincer tips"
        ),
        "height": 0.40,
        "height_variation": 0.10,
        "variant_tint_a": (1.0, 0.90, 0.86, 1.0),
        "variant_tint_b": (0.88, 1.0, 0.96, 1.0),
        "saturation": 1.36,
        "brightness": 1.06,
        "biome_tint_strength": 0.12,
        "night_emission_color": (0.36, 0.88, 1.0, 1.0),
        "night_emission_energy": 1.85,
        "night_emission_albedo": 0.52,
        "night_pulse_amount": 0.14,
        "night_pulse_speed": 0.28,
        "local_light_color": (0.30, 0.82, 1.0, 1.0),
        "local_light_energy": 1.15,
        "local_light_range": 6.5,
        "local_light_height_share": 0.48,
        "collision_radius_share": 0.55,
        "collision_height_share": 0.72,
        "combat_radius_share": 0.58,
        "ground_layer": 1,
        "minimum_ground_claim": 0.04,
        "above_water": 2.0,
        "below": 220.0,
        "minimum_arid": 0.0,
        "maximum_arid": 0.86,
        "minimum_frost": 0.0,
        "maximum_frost": 0.55,
        "max_slope": 28.0,
        "steady_over": 1.8,
        "steady_within": 0.90,
        "global_population": False,
        "cell_size": 88.0,
        "spawn_chance": 0.16,
        "pack_min": 2,
        "pack_max": 4,
        "pack_radius": 5.0,
        "maximum_instances": 8,
        "spawn_within": 200.0,
        "despawn_beyond": 268.0,
        "random_seed": 20268201,
        "colony_count": 2,
        "colony_near": 24.0,
        "colony_far": 58.0,
        "health": 48.0,
        "health_per_metre": 10.0,
        "toughness": 1,
        "respawn_delay": 14.0,
        "walk_speed": 1.35,
        "run_speed": 3.8,
        "move_acceleration": 16.0,
        "turn_speed": 9.0,
        "wander_radius": 14.0,
        "wander_pause": 2.2,
        "notice_range": 10.0,
        "flee_range": 6.0,
        "physics_within": 40.0,
        "skeletal_clips": True,
        "clip_attack": "Attack",
        "clip_speed_scale": 1.05,
        "clip_blend": 0.14,
        "attack_damage": 8.0,
        "attack_range": 0.55,
        "attack_radius": 0.48,
        "attack_windup": 0.32,
        "attack_cooldown": 1.1,
        "attack_knockback": 3.6,
        "roughness": 0.48,
        "specular": 0.36,
        "texture_relief": 1.20,
        "detail_scale": 11.0,
        "detail_amount": 0.12,
        "bump_scale": 16.0,
        "bump_strength": 0.14,
        "macro_scale": 1.0,
        "macro_amount": 0.10,
        "camera_rim_color": (1.0, 0.46, 0.32, 1.0),
        "camera_rim_energy": 0.32,
    },
    {
        "id": "prism_fin_dolphin",
        "display_name": "Prism-Fin Dolphin",
        "model": "prism_fin_dolphin",
        "enabled": True,
        "disposition": 0,  # FRIENDLY
        "move_set": 7,
        "locomotion": 0,
        "attack_style": 1,
        "paint_style": (
            "Silver-blue flank streaks, cream belly blaze, teal side-stripe, "
            "indigo flukes, gold dorsal marks, and a pink melon glow"
        ),
        "height": 0.58,
        "height_variation": 0.08,
        "variant_tint_a": (0.88, 0.98, 1.0, 1.0),
        "variant_tint_b": (1.0, 0.92, 0.96, 1.0),
        "saturation": 1.32,
        "brightness": 1.08,
        "biome_tint_strength": 0.10,
        "night_emission_color": (0.90, 0.72, 1.0, 1.0),
        "night_emission_energy": 1.70,
        "night_emission_albedo": 0.48,
        "night_pulse_amount": 0.12,
        "night_pulse_speed": 0.22,
        "local_light_color": (0.70, 0.82, 1.0, 1.0),
        "local_light_energy": 1.05,
        "local_light_range": 7.0,
        "local_light_height_share": 0.42,
        "collision_radius_share": 0.48,
        "collision_height_share": 0.70,
        "combat_radius_share": 0.52,
        "ground_layer": 1,
        "minimum_ground_claim": 0.03,
        "above_water": 1.5,
        "below": 180.0,
        "minimum_arid": 0.0,
        "maximum_arid": 0.70,
        "minimum_frost": 0.0,
        "maximum_frost": 0.62,
        "max_slope": 18.0,
        "steady_over": 2.4,
        "steady_within": 1.0,
        "global_population": False,
        "cell_size": 96.0,
        "spawn_chance": 0.10,
        "pack_min": 2,
        "pack_max": 3,
        "pack_radius": 6.5,
        "maximum_instances": 6,
        "spawn_within": 200.0,
        "despawn_beyond": 268.0,
        "random_seed": 20268202,
        "colony_count": 2,
        "colony_near": 28.0,
        "colony_far": 64.0,
        "health": 70.0,
        "health_per_metre": 14.0,
        "toughness": 0,
        "respawn_delay": 18.0,
        "walk_speed": 2.4,
        "run_speed": 6.4,
        "move_acceleration": 14.0,
        "turn_speed": 5.5,
        "wander_radius": 22.0,
        "wander_pause": 1.8,
        "notice_range": 16.0,
        "flee_range": 8.0,
        "physics_within": 48.0,
        "provoked_seconds": 6.0,
        "skeletal_clips": True,
        "clip_attack": "Attack",
        "clip_speed_scale": 1.10,
        "clip_blend": 0.18,
        "attack_damage": 9.0,
        "attack_range": 0.70,
        "attack_radius": 0.50,
        "attack_windup": 0.36,
        "attack_cooldown": 1.4,
        "attack_knockback": 4.2,
        "roughness": 0.32,
        "specular": 0.48,
        "texture_relief": 1.05,
        "detail_scale": 8.0,
        "detail_amount": 0.09,
        "bump_scale": 12.0,
        "bump_strength": 0.10,
        "macro_scale": 0.85,
        "macro_amount": 0.08,
        "camera_rim_color": (0.46, 0.88, 1.0, 1.0),
        "camera_rim_energy": 0.36,
    },
    {
        "id": "glimmer_crest_bird",
        "display_name": "Glimmer-Crest Bird",
        "model": "glimmer_crest_bird",
        "enabled": True,
        "disposition": 1,
        "move_set": 7,
        "locomotion": 0,
        "attack_style": 1,
        "paint_style": (
            "Violet body streaks, gold breast blaze, teal wing bands, cream "
            "face, magenta crest discs, and lime tail chevrons"
        ),
        "height": 0.56,
        "height_variation": 0.12,
        "variant_tint_a": (0.94, 0.88, 1.0, 1.0),
        "variant_tint_b": (1.0, 0.96, 0.82, 1.0),
        "saturation": 1.40,
        "brightness": 1.06,
        "biome_tint_strength": 0.11,
        "night_emission_color": (0.95, 0.40, 0.78, 1.0),
        "night_emission_energy": 1.90,
        "night_emission_albedo": 0.50,
        "night_pulse_amount": 0.16,
        "night_pulse_speed": 0.32,
        "local_light_color": (0.90, 0.42, 0.80, 1.0),
        "local_light_energy": 1.10,
        "local_light_range": 6.8,
        "local_light_height_share": 0.70,
        "collision_radius_share": 0.28,
        "collision_height_share": 0.84,
        "combat_radius_share": 0.40,
        "ground_layer": 1,
        "minimum_ground_claim": 0.04,
        "above_water": 4.0,
        "below": 380.0,
        "minimum_arid": 0.0,
        "maximum_arid": 0.80,
        "minimum_frost": 0.0,
        "maximum_frost": 0.76,
        "max_slope": 26.0,
        "steady_over": 1.8,
        "steady_within": 0.90,
        "global_population": False,
        "cell_size": 80.0,
        "spawn_chance": 0.18,
        "pack_min": 2,
        "pack_max": 4,
        "pack_radius": 6.0,
        "maximum_instances": 8,
        "spawn_within": 200.0,
        "despawn_beyond": 268.0,
        "random_seed": 20268203,
        "colony_count": 2,
        "colony_near": 22.0,
        "colony_far": 56.0,
        "health": 36.0,
        "health_per_metre": 8.0,
        "toughness": 0,
        "respawn_delay": 12.0,
        "walk_speed": 1.70,
        "run_speed": 5.8,
        "move_acceleration": 20.0,
        "turn_speed": 10.0,
        "wander_radius": 20.0,
        "wander_pause": 1.6,
        "notice_range": 14.0,
        "flee_range": 8.5,
        "physics_within": 40.0,
        "skeletal_clips": True,
        "clip_attack": "Attack",
        "clip_speed_scale": 1.20,
        "clip_blend": 0.12,
        "attack_damage": 6.0,
        "attack_range": 0.45,
        "attack_radius": 0.36,
        "attack_windup": 0.28,
        "attack_cooldown": 0.95,
        "attack_knockback": 2.8,
        "roughness": 0.52,
        "specular": 0.30,
        "texture_relief": 1.18,
        "detail_scale": 12.0,
        "detail_amount": 0.13,
        "bump_scale": 17.0,
        "bump_strength": 0.13,
        "macro_scale": 1.05,
        "macro_amount": 0.10,
        "camera_rim_color": (0.72, 0.36, 1.0, 1.0),
        "camera_rim_energy": 0.34,
    },
    {
        "id": "lumen_hide_cow",
        "display_name": "Lumen-Hide Cow",
        "model": "lumen_hide_cow",
        "enabled": True,
        "disposition": 0,
        "move_set": 7,
        "locomotion": 0,
        "attack_style": 1,
        "paint_style": (
            "Cream hide streaks, lilac flank patches, indigo hooves, gold "
            "horn rings, teal udder glow, and a magenta tail switch"
        ),
        "height": 1.42,
        "height_variation": 0.08,
        "variant_tint_a": (1.0, 0.96, 0.90, 1.0),
        "variant_tint_b": (0.92, 0.90, 1.0, 1.0),
        "saturation": 1.28,
        "brightness": 1.02,
        "biome_tint_strength": 0.12,
        "night_emission_color": (0.30, 0.95, 0.86, 1.0),
        "night_emission_energy": 1.55,
        "night_emission_albedo": 0.46,
        "night_pulse_amount": 0.12,
        "night_pulse_speed": 0.18,
        "local_light_color": (0.34, 0.92, 0.82, 1.0),
        "local_light_energy": 1.20,
        "local_light_range": 8.0,
        "local_light_height_share": 0.38,
        "collision_radius_share": 0.36,
        "collision_height_share": 0.82,
        "combat_radius_share": 0.46,
        "ground_layer": 1,
        "minimum_ground_claim": 0.05,
        "above_water": 4.0,
        "below": 340.0,
        "minimum_arid": 0.0,
        "maximum_arid": 0.74,
        "minimum_frost": 0.0,
        "maximum_frost": 0.70,
        "max_slope": 20.0,
        "steady_over": 2.4,
        "steady_within": 1.05,
        "global_population": False,
        "cell_size": 100.0,
        "spawn_chance": 0.14,
        "pack_min": 2,
        "pack_max": 3,
        "pack_radius": 8.0,
        "maximum_instances": 6,
        "spawn_within": 210.0,
        "despawn_beyond": 278.0,
        "random_seed": 20268204,
        "colony_count": 2,
        "colony_near": 26.0,
        "colony_far": 60.0,
        "health": 150.0,
        "health_per_metre": 22.0,
        "toughness": 1,
        "respawn_delay": 24.0,
        "walk_speed": 1.40,
        "run_speed": 4.8,
        "move_acceleration": 16.0,
        "turn_speed": 5.5,
        "wander_radius": 18.0,
        "wander_pause": 3.2,
        "notice_range": 14.0,
        "flee_range": 7.0,
        "physics_within": 50.0,
        "graze": True,
        "graze_chance": 0.68,
        "graze_seconds": 6.0,
        "provoked_seconds": 8.0,
        "skeletal_clips": True,
        "clip_attack": "Attack",
        "clip_speed_scale": 1.00,
        "clip_blend": 0.18,
        "attack_damage": 12.0,
        "attack_range": 0.85,
        "attack_radius": 0.62,
        "attack_windup": 0.40,
        "attack_cooldown": 1.6,
        "attack_knockback": 6.0,
        "roughness": 0.64,
        "specular": 0.22,
        "texture_relief": 1.35,
        "detail_scale": 12.0,
        "detail_amount": 0.14,
        "bump_scale": 18.0,
        "bump_strength": 0.15,
        "macro_scale": 1.2,
        "macro_amount": 0.11,
        "camera_rim_color": (0.86, 0.72, 1.0, 1.0),
        "camera_rim_energy": 0.28,
    },
    {
        "id": "rift_hulk_monster",
        "display_name": "Rift-Hulk Monster",
        "model": "rift_hulk_monster",
        "enabled": True,
        "disposition": 2,  # HOSTILE
        "move_set": 7,
        "locomotion": 0,
        "attack_style": 1,
        "paint_style": (
            "Charcoal hide streaks, ember flank bands, bone-cream muzzle, "
            "toxic green back spines, red maw, and gold knuckle plates"
        ),
        "height": 2.10,
        "height_variation": 0.07,
        "variant_tint_a": (1.0, 0.90, 0.84, 1.0),
        "variant_tint_b": (0.86, 1.0, 0.88, 1.0),
        "saturation": 1.30,
        "brightness": 1.04,
        "biome_tint_strength": 0.08,
        "night_emission_color": (0.42, 1.0, 0.36, 1.0),
        "night_emission_energy": 2.10,
        "night_emission_albedo": 0.44,
        "night_pulse_amount": 0.18,
        "night_pulse_speed": 0.20,
        "local_light_color": (0.46, 1.0, 0.32, 1.0),
        "local_light_energy": 1.55,
        "local_light_range": 11.0,
        "local_light_height_share": 0.62,
        "collision_radius_share": 0.34,
        "collision_height_share": 0.88,
        "combat_radius_share": 0.48,
        "ground_layer": 0,
        "minimum_ground_claim": 0.0,
        "above_water": 5.0,
        "below": 420.0,
        "minimum_arid": 0.0,
        "maximum_arid": 1.0,
        "minimum_frost": 0.0,
        "maximum_frost": 0.90,
        "max_slope": 24.0,
        "steady_over": 2.8,
        "steady_within": 1.15,
        "global_population": False,
        "cell_size": 120.0,
        "spawn_chance": 0.08,
        "pack_min": 1,
        "pack_max": 1,
        "pack_radius": 4.0,
        "maximum_instances": 3,
        "spawn_within": 220.0,
        "despawn_beyond": 290.0,
        "random_seed": 20268205,
        "colony_count": 1,
        "colony_near": 48.0,
        "colony_far": 78.0,
        "health": 260.0,
        "health_per_metre": 32.0,
        "toughness": 2,
        "respawn_delay": 32.0,
        "walk_speed": 2.0,
        "run_speed": 6.6,
        "move_acceleration": 18.0,
        "turn_speed": 5.0,
        "wander_radius": 16.0,
        "wander_pause": 1.4,
        "notice_range": 22.0,
        "flee_range": 0.0,
        "physics_within": 55.0,
        "skeletal_clips": True,
        "clip_attack": "Attack",
        "clip_speed_scale": 0.95,
        "clip_blend": 0.16,
        "attack_damage": 28.0,
        "attack_range": 1.6,
        "attack_radius": 1.05,
        "attack_windup": 0.46,
        "attack_cooldown": 2.1,
        "attack_knockback": 12.0,
        "roughness": 0.70,
        "specular": 0.20,
        "texture_relief": 1.40,
        "detail_scale": 9.0,
        "detail_amount": 0.14,
        "bump_scale": 14.0,
        "bump_strength": 0.16,
        "macro_scale": 0.90,
        "macro_amount": 0.12,
        "camera_rim_color": (1.0, 0.42, 0.22, 1.0),
        "camera_rim_energy": 0.40,
    },
    {
        "id": "violet_seeker_alien",
        "display_name": "Violet Seeker",
        "model": "violet_seeker_alien",
        "enabled": True,
        "disposition": 2,
        "move_set": 7,
        "locomotion": 0,
        "attack_style": 1,
        "paint_style": (
            "Violet skin streaks, lavender belly blaze, teal eye discs, gold "
            "knuckle marks, indigo limb bands, and pink cranial membranes"
        ),
        "height": 1.76,
        "height_variation": 0.08,
        "variant_tint_a": (0.92, 0.86, 1.0, 1.0),
        "variant_tint_b": (0.86, 1.0, 1.0, 1.0),
        "saturation": 1.38,
        "brightness": 1.05,
        "biome_tint_strength": 0.09,
        "night_emission_color": (0.28, 0.92, 1.0, 1.0),
        "night_emission_energy": 2.00,
        "night_emission_albedo": 0.50,
        "night_pulse_amount": 0.15,
        "night_pulse_speed": 0.26,
        "local_light_color": (0.32, 0.88, 1.0, 1.0),
        "local_light_energy": 1.35,
        "local_light_range": 9.0,
        "local_light_height_share": 0.78,
        "collision_radius_share": 0.24,
        "collision_height_share": 0.90,
        "combat_radius_share": 0.40,
        "ground_layer": 0,
        "minimum_ground_claim": 0.0,
        "above_water": 4.0,
        "below": 400.0,
        "minimum_arid": 0.0,
        "maximum_arid": 1.0,
        "minimum_frost": 0.0,
        "maximum_frost": 0.88,
        "max_slope": 26.0,
        "steady_over": 2.2,
        "steady_within": 1.0,
        "global_population": False,
        "cell_size": 110.0,
        "spawn_chance": 0.10,
        "pack_min": 1,
        "pack_max": 2,
        "pack_radius": 5.5,
        "maximum_instances": 4,
        "spawn_within": 210.0,
        "despawn_beyond": 278.0,
        "random_seed": 20268206,
        "colony_count": 1,
        "colony_near": 40.0,
        "colony_far": 72.0,
        "health": 140.0,
        "health_per_metre": 18.0,
        "toughness": 0,
        "respawn_delay": 20.0,
        "walk_speed": 2.2,
        "run_speed": 7.4,
        "move_acceleration": 22.0,
        "turn_speed": 8.0,
        "wander_radius": 18.0,
        "wander_pause": 1.5,
        "notice_range": 20.0,
        "flee_range": 0.0,
        "physics_within": 50.0,
        "skeletal_clips": True,
        "clip_attack": "Attack",
        "clip_speed_scale": 1.10,
        "clip_blend": 0.14,
        "attack_damage": 16.0,
        "attack_range": 1.15,
        "attack_radius": 0.70,
        "attack_windup": 0.34,
        "attack_cooldown": 1.35,
        "attack_knockback": 7.0,
        "roughness": 0.42,
        "specular": 0.38,
        "texture_relief": 1.12,
        "detail_scale": 10.0,
        "detail_amount": 0.10,
        "bump_scale": 14.0,
        "bump_strength": 0.11,
        "macro_scale": 0.95,
        "macro_amount": 0.09,
        "camera_rim_color": (0.62, 0.36, 1.0, 1.0),
        "camera_rim_energy": 0.38,
    },
    {
        "id": "amber_stalker_alien",
        "display_name": "Amber Stalker",
        "model": "amber_stalker_alien",
        "enabled": True,
        "disposition": 2,
        "move_set": 7,
        "locomotion": 0,
        "attack_style": 1,
        "paint_style": (
            "Amber carapace bands, rust shoulder plates, cream joints, teal "
            "glow seams, dark claws, and a gold cranial crest"
        ),
        "height": 1.52,
        "height_variation": 0.08,
        "variant_tint_a": (1.0, 0.92, 0.80, 1.0),
        "variant_tint_b": (0.90, 1.0, 0.94, 1.0),
        "saturation": 1.34,
        "brightness": 1.04,
        "biome_tint_strength": 0.10,
        "night_emission_color": (0.22, 0.95, 0.88, 1.0),
        "night_emission_energy": 1.95,
        "night_emission_albedo": 0.48,
        "night_pulse_amount": 0.14,
        "night_pulse_speed": 0.24,
        "local_light_color": (0.28, 0.90, 0.80, 1.0),
        "local_light_energy": 1.30,
        "local_light_range": 8.5,
        "local_light_height_share": 0.72,
        "collision_radius_share": 0.30,
        "collision_height_share": 0.88,
        "combat_radius_share": 0.46,
        "ground_layer": 0,
        "minimum_ground_claim": 0.0,
        "above_water": 4.0,
        "below": 400.0,
        "minimum_arid": 0.08,
        "maximum_arid": 1.0,
        "minimum_frost": 0.0,
        "maximum_frost": 0.70,
        "max_slope": 25.0,
        "steady_over": 2.2,
        "steady_within": 1.0,
        "global_population": False,
        "cell_size": 110.0,
        "spawn_chance": 0.10,
        "pack_min": 1,
        "pack_max": 2,
        "pack_radius": 5.0,
        "maximum_instances": 4,
        "spawn_within": 210.0,
        "despawn_beyond": 278.0,
        "random_seed": 20268207,
        "colony_count": 1,
        "colony_near": 44.0,
        "colony_far": 76.0,
        "health": 165.0,
        "health_per_metre": 20.0,
        "toughness": 1,
        "respawn_delay": 22.0,
        "walk_speed": 2.0,
        "run_speed": 6.8,
        "move_acceleration": 20.0,
        "turn_speed": 7.5,
        "wander_radius": 16.0,
        "wander_pause": 1.6,
        "notice_range": 18.0,
        "flee_range": 0.0,
        "physics_within": 50.0,
        "skeletal_clips": True,
        "clip_attack": "Attack",
        "clip_speed_scale": 1.05,
        "clip_blend": 0.14,
        "attack_damage": 18.0,
        "attack_range": 1.25,
        "attack_radius": 0.78,
        "attack_windup": 0.36,
        "attack_cooldown": 1.45,
        "attack_knockback": 8.0,
        "roughness": 0.50,
        "specular": 0.34,
        "texture_relief": 1.22,
        "detail_scale": 10.0,
        "detail_amount": 0.12,
        "bump_scale": 15.0,
        "bump_strength": 0.13,
        "macro_scale": 1.0,
        "macro_amount": 0.10,
        "camera_rim_color": (1.0, 0.62, 0.22, 1.0),
        "camera_rim_energy": 0.36,
    },
    {
        "id": "glass_coil_octopus",
        "display_name": "Glass-Coil Octopus",
        "model": "glass_coil_octopus",
        "enabled": True,
        "disposition": 1,
        "move_set": 7,
        "locomotion": 0,
        "attack_style": 1,
        "paint_style": (
            "Teal mantle bands, violet arm streaks, gold sucker rings, cream "
            "underside, magenta arm-tip spots, and lime eye discs"
        ),
        "height": 0.50,
        "height_variation": 0.10,
        "variant_tint_a": (0.84, 1.0, 1.0, 1.0),
        "variant_tint_b": (0.96, 0.84, 1.0, 1.0),
        "saturation": 1.42,
        "brightness": 1.07,
        "biome_tint_strength": 0.11,
        "night_emission_color": (0.72, 1.0, 0.40, 1.0),
        "night_emission_energy": 1.80,
        "night_emission_albedo": 0.50,
        "night_pulse_amount": 0.16,
        "night_pulse_speed": 0.28,
        "local_light_color": (0.46, 1.0, 0.62, 1.0),
        "local_light_energy": 1.15,
        "local_light_range": 6.5,
        "local_light_height_share": 0.52,
        "collision_radius_share": 0.50,
        "collision_height_share": 0.70,
        "combat_radius_share": 0.56,
        "ground_layer": 1,
        "minimum_ground_claim": 0.03,
        "above_water": 1.8,
        "below": 200.0,
        "minimum_arid": 0.0,
        "maximum_arid": 0.72,
        "minimum_frost": 0.0,
        "maximum_frost": 0.50,
        "max_slope": 22.0,
        "steady_over": 2.0,
        "steady_within": 0.95,
        "global_population": False,
        "cell_size": 90.0,
        "spawn_chance": 0.12,
        "pack_min": 1,
        "pack_max": 2,
        "pack_radius": 5.0,
        "maximum_instances": 5,
        "spawn_within": 200.0,
        "despawn_beyond": 268.0,
        "random_seed": 20268208,
        "colony_count": 2,
        "colony_near": 30.0,
        "colony_far": 62.0,
        "health": 80.0,
        "health_per_metre": 14.0,
        "toughness": 0,
        "respawn_delay": 16.0,
        "walk_speed": 1.25,
        "run_speed": 3.6,
        "move_acceleration": 12.0,
        "turn_speed": 7.0,
        "wander_radius": 12.0,
        "wander_pause": 2.4,
        "notice_range": 11.0,
        "flee_range": 6.5,
        "physics_within": 40.0,
        "skeletal_clips": True,
        "clip_attack": "Attack",
        "clip_speed_scale": 1.00,
        "clip_blend": 0.16,
        "attack_damage": 10.0,
        "attack_range": 0.80,
        "attack_radius": 0.70,
        "attack_windup": 0.38,
        "attack_cooldown": 1.5,
        "attack_knockback": 4.5,
        "roughness": 0.28,
        "specular": 0.52,
        "texture_relief": 1.08,
        "detail_scale": 9.0,
        "detail_amount": 0.10,
        "bump_scale": 13.0,
        "bump_strength": 0.11,
        "macro_scale": 0.80,
        "macro_amount": 0.08,
        "camera_rim_color": (0.30, 1.0, 0.86, 1.0),
        "camera_rim_energy": 0.38,
    },
    {
        "id": "lantern_orb_spider",
        "display_name": "Lantern-Orb Spider",
        "model": "lantern_orb_spider",
        "enabled": True,
        "disposition": 2,
        "move_set": 7,
        "locomotion": 0,
        "attack_style": 1,
        "paint_style": (
            "Violet-black body streaks, gold abdomen orb, teal limb rings, "
            "cream fangs, magenta hourglass, and lime eye discs"
        ),
        "height": 0.38,
        "height_variation": 0.10,
        "variant_tint_a": (0.92, 0.86, 1.0, 1.0),
        "variant_tint_b": (1.0, 0.94, 0.78, 1.0),
        "saturation": 1.40,
        "brightness": 1.05,
        "biome_tint_strength": 0.10,
        "night_emission_color": (1.0, 0.78, 0.28, 1.0),
        "night_emission_energy": 2.20,
        "night_emission_albedo": 0.54,
        "night_pulse_amount": 0.18,
        "night_pulse_speed": 0.30,
        "local_light_color": (1.0, 0.72, 0.24, 1.0),
        "local_light_energy": 1.25,
        "local_light_range": 6.2,
        "local_light_height_share": 0.46,
        "collision_radius_share": 0.52,
        "collision_height_share": 0.68,
        "combat_radius_share": 0.56,
        "ground_layer": 0,
        "minimum_ground_claim": 0.0,
        "above_water": 3.0,
        "below": 360.0,
        "minimum_arid": 0.0,
        "maximum_arid": 1.0,
        "minimum_frost": 0.0,
        "maximum_frost": 0.72,
        "max_slope": 30.0,
        "steady_over": 1.6,
        "steady_within": 0.85,
        "global_population": False,
        "cell_size": 86.0,
        "spawn_chance": 0.14,
        "pack_min": 1,
        "pack_max": 3,
        "pack_radius": 4.5,
        "maximum_instances": 6,
        "spawn_within": 200.0,
        "despawn_beyond": 268.0,
        "random_seed": 20268209,
        "colony_count": 2,
        "colony_near": 32.0,
        "colony_far": 64.0,
        "health": 42.0,
        "health_per_metre": 9.0,
        "toughness": 0,
        "respawn_delay": 13.0,
        "walk_speed": 1.80,
        "run_speed": 5.2,
        "move_acceleration": 20.0,
        "turn_speed": 11.0,
        "wander_radius": 12.0,
        "wander_pause": 1.4,
        "notice_range": 13.0,
        "flee_range": 0.0,
        "physics_within": 40.0,
        "skeletal_clips": True,
        "clip_attack": "Attack",
        "clip_speed_scale": 1.15,
        "clip_blend": 0.12,
        "attack_damage": 11.0,
        "attack_range": 0.50,
        "attack_radius": 0.42,
        "attack_windup": 0.26,
        "attack_cooldown": 1.05,
        "attack_knockback": 3.4,
        "roughness": 0.46,
        "specular": 0.34,
        "texture_relief": 1.16,
        "detail_scale": 11.0,
        "detail_amount": 0.12,
        "bump_scale": 16.0,
        "bump_strength": 0.13,
        "macro_scale": 0.95,
        "macro_amount": 0.09,
        "camera_rim_color": (1.0, 0.72, 0.22, 1.0),
        "camera_rim_energy": 0.36,
    },
    {
        "id": "star_mane_hound",
        "display_name": "Star-Mane Hound",
        "model": "star_mane_hound",
        "enabled": True,
        "disposition": 0,
        "move_set": 7,
        "locomotion": 0,
        "attack_style": 1,
        "paint_style": (
            "Warm sand coat streaks, cream chest blaze, indigo ears and socks, "
            "gold mane marks, teal eye rings, and a pink tail tip"
        ),
        "height": 0.80,
        "height_variation": 0.10,
        "variant_tint_a": (1.0, 0.94, 0.86, 1.0),
        "variant_tint_b": (0.90, 0.96, 1.0, 1.0),
        "saturation": 1.30,
        "brightness": 1.04,
        "biome_tint_strength": 0.12,
        "night_emission_color": (0.28, 0.90, 1.0, 1.0),
        "night_emission_energy": 1.60,
        "night_emission_albedo": 0.46,
        "night_pulse_amount": 0.12,
        "night_pulse_speed": 0.22,
        "local_light_color": (0.34, 0.86, 1.0, 1.0),
        "local_light_energy": 1.10,
        "local_light_range": 7.2,
        "local_light_height_share": 0.58,
        "collision_radius_share": 0.34,
        "collision_height_share": 0.80,
        "combat_radius_share": 0.46,
        "ground_layer": 1,
        "minimum_ground_claim": 0.04,
        "above_water": 4.0,
        "below": 360.0,
        "minimum_arid": 0.0,
        "maximum_arid": 0.82,
        "minimum_frost": 0.0,
        "maximum_frost": 0.74,
        "max_slope": 24.0,
        "steady_over": 2.0,
        "steady_within": 0.95,
        "global_population": False,
        "cell_size": 90.0,
        "spawn_chance": 0.16,
        "pack_min": 2,
        "pack_max": 3,
        "pack_radius": 6.0,
        "maximum_instances": 6,
        "spawn_within": 200.0,
        "despawn_beyond": 268.0,
        "random_seed": 20268210,
        "colony_count": 2,
        "colony_near": 22.0,
        "colony_far": 54.0,
        "health": 90.0,
        "health_per_metre": 16.0,
        "toughness": 0,
        "respawn_delay": 16.0,
        "walk_speed": 1.90,
        "run_speed": 7.0,
        "move_acceleration": 22.0,
        "turn_speed": 8.5,
        "wander_radius": 18.0,
        "wander_pause": 2.0,
        "notice_range": 15.0,
        "flee_range": 7.5,
        "physics_within": 45.0,
        "provoked_seconds": 8.0,
        "skeletal_clips": True,
        "clip_attack": "Attack",
        "clip_speed_scale": 1.12,
        "clip_blend": 0.14,
        "attack_damage": 10.0,
        "attack_range": 0.65,
        "attack_radius": 0.48,
        "attack_windup": 0.30,
        "attack_cooldown": 1.15,
        "attack_knockback": 4.8,
        "roughness": 0.60,
        "specular": 0.24,
        "texture_relief": 1.28,
        "detail_scale": 13.0,
        "detail_amount": 0.14,
        "bump_scale": 18.0,
        "bump_strength": 0.15,
        "macro_scale": 1.15,
        "macro_amount": 0.11,
        "camera_rim_color": (1.0, 0.78, 0.42, 1.0),
        "camera_rim_energy": 0.30,
    },
)


MATERIAL_KEYS = (
    "roughness",
    "specular",
    "texture_relief",
    "detail_scale",
    "detail_amount",
    "bump_scale",
    "bump_strength",
    "macro_scale",
    "macro_amount",
    "camera_rim_energy",
)


def godot_value(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        text = f"{value:.6f}".rstrip("0").rstrip(".")
        return text + ".0" if "." not in text else text
    if isinstance(value, tuple) and len(value) == 4:
        return "Color({})".format(", ".join(
            godot_value(float(component)) for component in value))
    if isinstance(value, str):
        return '"{}"'.format(
            value.replace("\\", "\\\\").replace('"', '\\"'))
    raise TypeError(f"unsupported Godot value: {value!r}")


def write_material(definition: dict[str, object]) -> None:
    material = [
        "[gd_resource type=\"ShaderMaterial\" load_steps=2 format=3]",
        "",
        (
            "[ext_resource type=\"Shader\" "
            "path=\"res://shaders/vivid/vivid_surface.gdshader\" "
            "id=\"1_shader\"]"
        ),
        "",
        "[resource]",
        f"resource_name = {godot_value(definition['display_name'] + ' Surface')}",
        "shader = ExtResource(\"1_shader\")",
        "shader_parameter/base_color = Color(1.0, 1.0, 1.0, 1.0)",
        "shader_parameter/use_vertex_color = true",
        f"shader_parameter/saturation = {godot_value(definition['saturation'])}",
        f"shader_parameter/brightness = {godot_value(definition['brightness'])}",
        "shader_parameter/metallic = 0.0",
        "shader_parameter/roughness_variation = 0.18",
        "shader_parameter/relief_width = 2.0",
        "shader_parameter/region_albedo = 0.0",
        "shader_parameter/region_sheen = 0.28",
        "shader_parameter/region_rim = 0.42",
        "shader_parameter/detail_near = 10.0",
        "shader_parameter/detail_far = 52.0",
        (
            "shader_parameter/camera_rim_color = "
            + godot_value(definition["camera_rim_color"])
        ),
        (
            "shader_parameter/night_emission_color = "
            + godot_value(definition["night_emission_color"])
        ),
        (
            "shader_parameter/night_emission_energy = "
            + godot_value(definition["night_emission_energy"])
        ),
        "shader_parameter/night_emission_from_texture_alpha = true",
    ]
    for key in MATERIAL_KEYS:
        material.append(
            f"shader_parameter/{key} = {godot_value(definition[key])}")
    material.append("")
    path = MATERIAL_DIR / f"{definition['id']}.tres"
    path.write_text("\n".join(material), encoding="utf-8", newline="\n")


def write_species(definition: dict[str, object]) -> None:
    species = [
        (
            "[gd_resource type=\"Resource\" script_class=\"FaunaSpecies\" "
            "load_steps=5 format=3]"
        ),
        "",
        (
            "[ext_resource type=\"Script\" "
            "path=\"res://game/fauna/fauna_species.gd\" id=\"1_species\"]"
        ),
        (
            "[ext_resource type=\"PackedScene\" "
            f"path=\"res://assets/runtime/fauna/models/{definition['model']}.glb\" "
            "id=\"2_model\"]"
        ),
        (
            "[ext_resource type=\"ShaderMaterial\" "
            f"path=\"res://game/fauna/materials/{definition['id']}.tres\" "
            "id=\"3_material\"]"
        ),
        (
            "[ext_resource type=\"Texture2D\" "
            f"path=\"res://assets/runtime/biomes/paint/{definition['model']}_paint.png\" "
            "id=\"4_paint\"]"
        ),
        "",
        "[resource]",
        "script = ExtResource(\"1_species\")",
        "model = ExtResource(\"2_model\")",
        "material = ExtResource(\"3_material\")",
        "paint_texture = ExtResource(\"4_paint\")",
    ]
    skip = {
        "id",
        "model",
        "roughness",
        "specular",
        "texture_relief",
        "detail_scale",
        "detail_amount",
        "bump_scale",
        "bump_strength",
        "macro_scale",
        "macro_amount",
        "camera_rim_color",
        "camera_rim_energy",
    }
    aliases = {"id": "species_id"}
    species.append(f"species_id = {godot_value(definition['id'])}")
    for key, value in definition.items():
        if key in skip or key == "id":
            continue
        property_name = aliases.get(key, key)
        species.append(f"{property_name} = {godot_value(value)}")
    species.append("")
    path = SPECIES_DIR / f"{definition['id']}.tres"
    path.write_text("\n".join(species), encoding="utf-8", newline="\n")


def write_scene() -> None:
    scene = [
        "[gd_scene load_steps=5 format=3]",
        "",
        (
            "[ext_resource type=\"Script\" "
            "path=\"res://game/fauna/fauna_spawner.gd\" id=\"1_spawner\"]"
        ),
        (
            "[ext_resource type=\"Script\" "
            "path=\"res://game/fauna/fauna_species.gd\" "
            "id=\"2_species_script\"]"
        ),
    ]
    for index, definition in enumerate(SPECIES, start=3):
        scene.append(
            "[ext_resource type=\"Resource\" "
            f"path=\"res://game/fauna/species/{definition['id']}.tres\" "
            f"id=\"{index}_species\"]"
        )
    scene.extend([
        "",
        (
            "[node name=\"FaunaPopulations\" type=\"Node3D\"]"
        ),
        "script = ExtResource(\"1_spawner\")",
        (
            "species = Array[ExtResource(\"2_species_script\")](["
            + ", ".join(
                f"ExtResource(\"{index}_species\")"
                for index in range(3, len(SPECIES) + 3))
            + "])"
        ),
        # FaunaSpawner discovers its parent Planet and conventional
        # GlobalGrass/VacationersLanding siblings. PackedScene NodePaths cannot retain
        # references outside this scene root; exports remain available for a
        # custom hierarchy.
        "survey_interval = 1.25",
        "initial_survey_delay = 1.5",
        "max_spawns_per_survey = 2",
        "candidate_limit_per_species = 128",
        "light_limit = 7",
        "lights_within = 95.0",
        "light_follow_speed = 9.0",
        "light_fade_speed = 5.0",
        "",
    ])
    SCENE_PATH.write_text("\n".join(scene), encoding="utf-8", newline="\n")


def main() -> None:
    SPECIES_DIR.mkdir(parents=True, exist_ok=True)
    MATERIAL_DIR.mkdir(parents=True, exist_ok=True)
    for definition in SPECIES:
        write_material(definition)
        write_species(definition)
    write_scene()
    print(
        f"Wrote {len(SPECIES)} fauna species, materials, and {SCENE_PATH}")


if __name__ == "__main__":
    main()
